'use strict';
const $ = (s,root=document)=>root.querySelector(s);
const app = $('#app');
const storageKey='little-sounds-v1';
const fresh=()=>({mastered:[],completed:[],mistakes:[],days:[],daily:{},grade:0});
let state=fresh();
try{const raw=JSON.parse(localStorage.getItem(storageKey));if(raw&&Array.isArray(raw.mastered)&&Array.isArray(raw.completed)&&Array.isArray(raw.days)&&Array.isArray(raw.mistakes))state={...fresh(),...raw};}catch{}
let page='home', selectedSound=0, filter='全部', grade=Math.max(0,Math.min(5,state.grade||0)), lesson=0, sentenceAnswered=false, challenge=null, activeAudio=null;
let soundPractice={kind:'phoneme',id:0,lesson:0}, spellingToken=0;
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const dayState=()=>state.daily[today()]||{sounds:[],sentences:[],challenge:false};
function save(){try{localStorage.setItem(storageKey,JSON.stringify(state));}catch{toast('浏览器未允许保存进度，本次仍可以继续练习。');}}
function activity(type,id){const d=today();if(!state.days.includes(d))state.days.push(d);const a=state.daily[d] ||= {sounds:[],sentences:[],challenge:false};if(type==='challenge')a.challenge=true;else if(!a[type].includes(id))a[type].push(id);save();}
function streak(){let n=0,d=new Date();if(!state.days.includes(today()))d.setDate(d.getDate()-1);while(state.days.includes(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`)){n++;d.setDate(d.getDate()-1);}return n;}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
const speaker='♪';
const mascot=`<svg class="mascot" viewBox="0 0 260 260" role="img" aria-label="戴耳机的紫色小星球"><ellipse cx="132" cy="231" rx="66" ry="11" fill="#c6d2b5" opacity=".5"/><path d="M87 193q-16 17-8 29q8 9 24-3M163 198q12 24 26 19q13-4 3-23" fill="#b9b2de" stroke="#8278b2" stroke-width="3"/><path d="M73 137q-36-9-36 11t41 23M187 144q32-29 39-14t-30 42" fill="#c8c1eb" stroke="#8278b2" stroke-width="3"/><path d="M127 46c-51-2-81 33-80 90s38 76 84 76 80-23 79-80-31-84-83-86z" fill="#c8c1eb" stroke="#a69acb" stroke-width="2"/><path d="M51 113Q43 36 128 31q84-2 85 85" fill="none" stroke="#315c49" stroke-width="13" stroke-linecap="round"/><path d="M51 100q-20-3-21 24v27q3 23 25 18" fill="#4d7d60" stroke="#315c49" stroke-width="5"/><rect x="45" y="104" width="18" height="61" rx="9" fill="#efca70"/><path d="M207 101q19-3 21 24v26q-3 23-24 18" fill="#4d7d60" stroke="#315c49" stroke-width="5"/><rect x="196" y="105" width="18" height="61" rx="9" fill="#efca70"/><ellipse cx="95" cy="130" rx="5" ry="8" fill="#384638"/><ellipse cx="164" cy="130" rx="5" ry="8" fill="#384638"/><path d="M111 151q18 22 36 0" fill="none" stroke="#384638" stroke-width="4" stroke-linecap="round"/><ellipse cx="82" cy="148" rx="12" ry="6" fill="#e4aac3"/><ellipse cx="177" cy="148" rx="12" ry="6" fill="#e4aac3"/><path d="m129 68 4 9 10 2-8 6 1 10-8-5-9 5 2-10-8-6 10-2z" fill="#f8df92"/><path d="M119 178q11 8 22 0" stroke="#b4a9d9" stroke-width="3" fill="none"/></svg>`;
function stats(){return `<div class="stats-row"><div class="stat"><span class="stat-icon">◉</span><div><strong>${state.mastered.length} <small>/ 44 个</small></strong><p>已掌握音标</p></div></div><div class="stat"><span class="stat-icon">≋</span><div><strong>${state.completed.length} <small>句</small></strong><p>已完成句子</p></div></div><div class="stat"><span class="stat-icon">☀</span><div><strong>${streak()} <small>天</small></strong><p>连续学习</p></div></div></div>`;}
function header(title,sub,tag,count=''){return `<div class="page-top"><div><div class="eyebrow">${tag}</div><h1>${title}</h1><p>${sub}</p></div>${count?`<span class="count">${count}</span>`:''}</div>`;}
function home(){return `<section class="hero simple-hero"><div class="hero-copy"><span class="pill">✦ 音标小星球</span><h1>听一听，<br><span>勇敢说出来！</span></h1><p>今天，从一个小声音开始。</p><a class="btn" href="#sounds">♪ 开始学音标 →</a></div><div class="hero-art"><div class="orbit"></div>${mascot}<div class="float-card one"><strong>/æ/</strong><span>🐱 cat</span></div><div class="float-card two"><strong>/iː/</strong><span>🐑 sheep</span></div></div></section><div class="start-cards"><a href="#sounds" class="start-card green"><span>🔤</span><h2>学音标</h2><p>先听音标 · 再拼单词</p><b>→</b></a><a href="#sentences" class="start-card purple"><span>💬</span><h2>练句子</h2><p>听一句 · 说一句</p><b>→</b></a><a href="#challenge" class="start-card yellow"><span>🎧</span><h2>玩听音</h2><p>听一听 · 选一选</p><b>→</b></a></div><a class="little-progress" href="#progress">✦ 已学 ${state.mastered.length} 个音标 · 已练 ${state.completed.length} 句 <span>我的成长 →</span></a>`;}
function sounds(){
 const s=SOUNDS[selectedSound],types=['全部','短元音','长元音','双元音','辅音'];
 if(soundPractice.lesson!==selectedSound)soundPractice={kind:'phoneme',id:selectedSound,lesson:selectedSound};
 const items=SOUNDS.filter(x=>filter==='全部'||(filter==='辅音'?x.id>=20:x.type===filter));
 return `<div class="simple-page-head"><h1>学音标 <span>🔤</span></h1><span>${selectedSound+1} / 44</span></div><section class="sound-focus"><div class="sound-type"><span class="pill">${s.type}</span></div>
 <div class="sound-steps"><button class="sound-step" data-practice-target="phoneme" aria-label="1 听音标 /${s.symbol}/"><span class="step-label">1 听音标 <b>♪</b></span><strong class="step-ipa">/${s.symbol}/</strong><small>点一下，跟着读</small></button><span class="step-arrow" aria-hidden="true">→</span><button class="sound-step word-step" data-practice-target="word" aria-label="2 听单词 ${s.word}"><span class="step-label">2 听单词 <b>♪</b></span><span class="step-word"><span role="img" aria-label="${s.zh}">${WORD_PICTURES[s.id]}</span><strong lang="en-GB">${s.word}</strong></span><small>${s.zh} · ${s.ipa}</small></button></div>
 <div class="blend-practice"><div class="blend-heading"><span>拆开读，再连起来</span><button class="text-link" id="spell-word">▷ 逐音拼读</button></div><div class="blend-chips" aria-label="${s.word} 的音标拆分">${s.parts.map((id,i)=>`<button class="phoneme-chip" data-part="${i}" data-phoneme="${id}" aria-label="第 ${i+1} 个音 /${SOUNDS[id].symbol}/">/${SOUNDS[id].symbol}/</button>`).join('<span class="blend-plus" aria-hidden="true">+</span>')}<span class="blend-plus" aria-hidden="true">→</span><button class="blend-word" data-practice-target="word" aria-label="听整个单词 ${s.word}" lang="en-GB">${s.word}</button></div></div>
 ${soundWaveMarkup()}<div class="sound-navigation"><button class="text-link" id="previous-sound" ${selectedSound===0?'disabled':''}>← 上一个</button><button class="btn" id="master-sound">${selectedSound===43?'我会了，完成 ✓':'会了，下一个 →'}</button></div></section><details class="sound-picker"><summary>▦ 选其他音标 <span>⌄</span></summary><div class="filters">${types.map(t=>`<button class="filter ${filter===t?'active':''}" data-filter="${t}" aria-pressed="${filter===t}">${t}</button>`).join('')}</div><div class="sound-grid">${items.map(x=>`<button class="sound-tile ${x.id===selectedSound?'selected':''}" data-sound="${x.id}" aria-label="学习音标 ${x.symbol}，例词 ${x.word}" aria-pressed="${x.id===selectedSound}">${state.mastered.includes(x.id)?'<span class="mastered">✓</span>':''}<strong>/${x.symbol}/</strong><small>${x.word}</small></button>`).join('')}</div></details>`;
}
function soundWaveMarkup(){const isPhoneme=soundPractice.kind==='phoneme';return waveComparisonMarkup(isPhoneme?SOUNDS[soundPractice.id].symbol:SOUNDS[selectedSound].word,true,isPhoneme?'phoneme':'word');}
function refreshSoundPractice(){
 if(page!=='sounds')return;
 app.querySelectorAll('[data-practice-target]').forEach(b=>{const active=b.dataset.practiceTarget===soundPractice.kind&&(soundPractice.kind==='word'||soundPractice.id===selectedSound);b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});
 app.querySelectorAll('[data-part]').forEach(b=>{const active=soundPractice.kind==='phoneme'&&Number(b.dataset.phoneme)===soundPractice.id&&(soundPractice.part===undefined||Number(b.dataset.part)===soundPractice.part);b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});
}
function selectSoundPractice(target,cancelSequence=true){
 if(cancelSequence)spellingToken++;
 const changed=soundPractice.kind!==target.kind||(target.kind==='phoneme'&&soundPractice.id!==target.id);
 soundPractice={...target,lesson:selectedSound};
 if(changed){clearRecording();stopAudio();$('#wave-comparison').outerHTML=soundWaveMarkup();mountWaveComparison();}
 refreshSoundPractice();return waveComparison;
}
async function spellWord(){
 const token=++spellingToken,lessonAtStart=selectedSound,s=SOUNDS[lessonAtStart];
 for(let i=0;i<s.parts.length;i++){
  if(token!==spellingToken||page!=='sounds'||selectedSound!==lessonAtStart)return;
  const id=s.parts[i],comparison=selectSoundPractice({kind:'phoneme',id,part:i},false);
  comparison.status(`拆开读：/${SOUNDS[id].symbol}/`);
  if(!await comparison.play('reference'))return;
 }
 if(token!==spellingToken||page!=='sounds'||selectedSound!==lessonAtStart)return;
 const comparison=selectSoundPractice({kind:'word'},false);comparison.status(`连起来：${s.word}`);
 await comparison.play('reference');
}
function sentences(){const g=GRADES[grade],s=g.sentences[lesson];return `<div class="simple-page-head"><h1>练句子 <span>💬</span></h1><span>${lesson+1} / 6</span></div><div class="filters grade-buttons">${GRADES.map((g,i)=>`<button class="filter ${grade===i?'active':''}" data-grade="${i}" aria-pressed="${grade===i}">${g.name}</button>`).join('')}</div><section class="practice-card simple-practice"><div class="practice-meta"><span>${g.theme}</span><span>听 → 说 → 选</span></div><h2 lang="en-GB">${s[0]}</h2><p class="translation">${s[1]}</p>${waveComparisonMarkup(s[0],false)}<div class="quiz-box"><h3>选一选 ✦</h3><p lang="en">${s[2].replace('___','<span style="color:var(--green)">_____</span>')}</p><div class="options">${shuffleStable(s.slice(3),`${grade}-${lesson}`).map(w=>`<button class="option sentence-option" data-answer="${w}">${w}</button>`).join('')}</div><div class="feedback" id="sentence-feedback" role="status"></div></div><div class="next-row"><button class="text-link" id="prev-sentence" ${lesson===0?'disabled':''}>← 上一句</button><button class="btn" id="next-sentence">${lesson===5?'练完啦 ✓':'练好了，下一句 →'}</button></div></section>`;}
function shuffleStable(a,key){const shift=[...key].reduce((n,c)=>n+c.charCodeAt(0),0)%a.length;return [...a.slice(shift),...a.slice(0,shift)];}
function shuffled(a){return [...a].sort(()=>Math.random()-.5);}
function newChallenge(review=false){let pool=review&&state.mistakes.length?state.mistakes:SOUNDS.map(s=>s.id);pool=shuffled(pool).slice(0,5);challenge={questions:pool.map(id=>({id,options:shuffled([id,...shuffled(SOUNDS.filter(s=>s.id!==id&&!SOUNDS[id].ipa.includes(s.symbol)&&(id<20?s.id<20:s.id>=20)).map(s=>s.id)).slice(0,2)])})),index:0,score:0,answered:false,heard:false,finished:false};location.hash='#challenge';render();}
function challengePage(){if(!challenge)return `<div class="simple-page-head"><h1>玩听音 <span>🎧</span></h1></div><div class="challenge-card"><div class="big-icon">🎧</div><h2>听一听，选声音</h2><p>5 道小题，试试看！</p><button class="btn" id="start-challenge">开始玩 →</button>${state.mistakes.length?'<p><button class="text-link" id="review-challenge">再练练上次的声音</button></p>':''}</div>`;if(challenge.finished)return `<div class="challenge-card"><div class="big-icon">🌟</div><h2>答对 ${challenge.score} / ${challenge.questions.length} 题！</h2><p>${challenge.score===challenge.questions.length?'小耳朵真灵！':'再听一次，会更熟悉！'}</p><div class="actions" style="justify-content:center"><button class="btn" id="start-challenge">再玩一次 →</button><a class="btn light" href="#sounds">去学音标</a></div></div>`;const q=challenge.questions[challenge.index];return `<div class="simple-page-head"><h1>玩听音 <span>🎧</span></h1><span>${challenge.index+1} / ${challenge.questions.length}</span></div><div class="challenge-card"><div class="progress-track"><span style="width:${challenge.index/challenge.questions.length*100}%"></span></div><div class="big-icon">♪</div><h2>听到了哪个声音？</h2><button class="btn" id="hear-question">♪ 听一听</button><div class="options">${q.options.map(id=>`<button class="option challenge-option" data-choice="${id}" ${challenge.heard&&!challenge.answered?'':'disabled'}>/${SOUNDS[id].symbol}/</button>`).join('')}</div><div class="feedback" id="challenge-feedback" role="status">点“听一听”再选哦。</div><button class="btn" id="next-question" ${challenge.answered?'':'hidden'}>${challenge.index===challenge.questions.length-1?'看看结果':'下一题'} →</button></div>`;}
function progress(){return header('我的成长小花园','你认真练过的每一个声音，都在这里留下小小的足迹。','MY LITTLE GARDEN')+stats()+`<div class="achievement-grid">${[['🌱','勇敢开口',state.mastered.length>=1,'掌握第一个音标'],['🌼','句子小达人',state.completed.length>=6,'完成 6 句练习'],['☀','坚持小星星',streak()>=3,'连续学习 3 天']].map(a=>`<div class="achievement ${a[2]?'':'locked'}"><span class="medal">${a[0]}</span><h3>${a[1]} ${a[2]?'✓':''}</h3><p>${a[3]}</p></div>`).join('')}</div><div class="section-heading"><h2>我的音标复习本</h2>${state.mistakes.length?'<button class="text-link" id="review-challenge">开始复习 ↗</button>':''}</div>${state.mistakes.length?`<p class="muted">这些音标在听音挑战里答错过。再次答对后，它们会从复习本移出。</p><div class="saved-list">${state.mistakes.map(id=>`<button class="saved-pill" data-open-sound="${id}">/${SOUNDS[id].symbol}/</button>`).join('')}</div>`:'<div class="empty">复习本里暂时没有待巩固的音标。去听音挑战试一试吧！</div>'}<div class="section-heading"><h2>已经掌握的声音</h2><span class="muted">点击即可再听一遍</span></div>${state.mastered.length?`<div class="saved-list">${state.mastered.map(id=>`<button class="saved-pill" data-open-sound="${id}">/${SOUNDS[id].symbol}/</button>`).join('')}</div>`:'<div class="empty">从一个声音开始，你的小花园很快就会长大。<br><a class="text-link" href="#sounds">认识第一个音标 →</a></div>'}<div class="section-heading"><h2>句子练习进度</h2></div><div class="grade-strip">${GRADES.map((g,i)=>`<button class="grade-tile" data-grade-start="${i}"><strong>${state.completed.filter(id=>id.startsWith(i+'-')).length}<small style="font-size:13px"> / 6</small></strong><span>${g.name}</span></button>`).join('')}</div><p class="muted" style="margin-top:25px">成长记录保存在这个浏览器中，不跨设备同步。清除浏览器数据会清除记录。</p><button class="reset" id="reset-progress">重新开始 · 清空本机学习记录</button>`;}
function stopAudio(){if(activeAudio){activeAudio.pause();activeAudio=null;}if('speechSynthesis'in window)speechSynthesis.cancel();document.querySelectorAll('.audio-playing').forEach(b=>b.classList.remove('audio-playing'));}
async function playAudio(text,src,rate=1,button,onStarted){stopAudio();const audio=new Audio(src);activeAudio=audio;audio.playbackRate=rate;let started=false;const start=()=>{if(started)return;started=true;button?.classList.add('audio-playing');onStarted?.();};audio.onended=()=>button?.classList.remove('audio-playing');audio.onplaying=start;try{await audio.play();}catch{if(!text||!('speechSynthesis'in window)){toast('暂时无法播放，请检查浏览器声音设置后重试。');return;}const voices=speechSynthesis.getVoices(),voice=voices.find(v=>v.lang==='en-GB');if(!voice){toast('音频暂时不可用，请检查网络后重试。');return;}const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.voice=voice;u.rate=rate*.85;u.onstart=start;u.onend=()=>button?.classList.remove('audio-playing');u.onerror=()=>toast('朗读失败，请再试一次。');speechSynthesis.speak(u);}}
function wordAudio(word,button){playAudio(word,`audio/word-${word}.mp3`,1,button,()=>{if(page==='sounds')activity('sounds',selectedSound);});}
let waveComparison = null;
function clearRecording(){if(waveComparison){waveComparison.dispose();waveComparison=null;}}
function restartComparison(){
clearRecording();
const root=$('#wave-comparison');if(!root)return;
root.outerHTML=page==='sounds'?soundWaveMarkup():waveComparisonMarkup(GRADES[grade].sentences[lesson][0],false);
mountWaveComparison();
}
function mountWaveComparison(){
const root=$('#wave-comparison');if(!root)return;
const key=page==='sounds'?(soundPractice.kind==='phoneme'?`phoneme-${soundPractice.id}.mp3`:`word-${SOUNDS[selectedSound].word}.mp3`):`sentence-${grade}-${lesson}.mp3`;
waveComparison=new WaveComparison(root,{reference:REFERENCE_WAVES[key],source:()=>typeof EMBEDDED_AUDIO!=='undefined'?EMBEDDED_AUDIO[key]:`audio/${key}`,stopOther:stopAudio,onReference:()=>{if(page==='sounds')activity('sounds',selectedSound);}});
root.querySelectorAll('[data-reference-audio]').forEach(b=>waveComparison.bindPlay(b,Number(b.dataset.referenceAudio)));
refreshSoundPractice();
}
function render(){spellingToken++;clearRecording();app.innerHTML=page==='sounds'?sounds():page==='sentences'?sentences():page==='challenge'?challengePage():page==='progress'?progress():home();document.querySelectorAll('[data-nav]').forEach(a=>{a.classList.toggle('active',a.dataset.nav===page);if(a.dataset.nav===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});bind();mountWaveComparison();}
function bind(){
app.querySelectorAll('[data-practice-target]').forEach(b=>b.onclick=()=>{const target=b.dataset.practiceTarget==='word'?{kind:'word'}:{kind:'phoneme',id:selectedSound};selectSoundPractice(target).play('reference');});
app.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>selectSoundPractice({kind:'phoneme',id:Number(b.dataset.phoneme),part:Number(b.dataset.part)}).play('reference'));
if($('#spell-word'))$('#spell-word').onclick=()=>spellWord();
app.querySelectorAll('[data-grade-start]').forEach(b=>b.onclick=()=>{grade=Number(b.dataset.gradeStart);lesson=0;state.grade=grade;save();location.hash='#sentences';});app.querySelectorAll('[data-sound]').forEach(b=>b.onclick=()=>{selectedSound=Number(b.dataset.sound);stopAudio();render();window.scrollTo({top:0,behavior:'smooth'});});app.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;if(filter!=='全部'&&(filter==='辅音'?selectedSound<20:SOUNDS[selectedSound].type!==filter))selectedSound=SOUNDS.find(s=>filter==='辅音'?s.id>=20:s.type===filter).id;render();const picker=$('.sound-picker');if(picker)picker.open=true;});app.querySelectorAll('[data-audio-word]').forEach(b=>b.onclick=()=>wordAudio(b.dataset.audioWord,b));app.querySelectorAll('[data-open-sound]').forEach(b=>b.onclick=()=>{selectedSound=Number(b.dataset.openSound);filter='全部';location.hash='#sounds';});
if($('#master-sound'))$('#master-sound').onclick=()=>{if(!state.mastered.includes(selectedSound))state.mastered.push(selectedSound);activity('sounds',selectedSound);clearRecording();stopAudio();if(selectedSound<43){selectedSound++;render();waveComparison.play('reference');}else {restartComparison();showModal('<div class="finish-star">🌟</div><h2>44 个声音，练完啦！</h2><div class="actions"><a class="btn" href="#challenge" id="finish-to-challenge">玩听音 →</a><button class="btn light" id="sound-again">再学一遍</button></div>',()=>{$('#finish-to-challenge').onclick=()=>$('#modal').close();$('#sound-again').onclick=()=>{selectedSound=0;$('#modal').close();render();}});}};
if($('#previous-sound'))$('#previous-sound').onclick=()=>{stopAudio();selectedSound=Math.max(0,selectedSound-1);render();};
app.querySelectorAll('[data-slow-word]').forEach(b=>b.onclick=()=>playAudio(b.dataset.slowWord,`audio/word-${b.dataset.slowWord}.mp3`,.75,b,()=>activity('sounds',selectedSound)));
app.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>{clearRecording();stopAudio();grade=Number(b.dataset.grade);lesson=0;sentenceAnswered=false;state.grade=grade;save();render();});app.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>changeLesson(Number(b.dataset.lesson)));app.querySelectorAll('[data-sentence-audio]').forEach(b=>b.onclick=()=>playAudio(GRADES[grade].sentences[lesson][0],`audio/sentence-${grade}-${lesson}.mp3`,Number(b.dataset.sentenceAudio),b));

app.querySelectorAll('.sentence-option').forEach(b=>b.onclick=()=>{if(sentenceAnswered)return;const answer=GRADES[grade].sentences[lesson][3],correct=b.dataset.answer===answer;if(correct){sentenceAnswered=true;b.classList.add('correct');$('#sentence-feedback').textContent='✓ 对啦！再读一句吧。';app.querySelectorAll('.sentence-option').forEach(x=>x.disabled=true);}else{b.classList.add('wrong');b.disabled=true;$('#sentence-feedback').textContent='再试一次，上面有提示哦。';}});
if($('#prev-sentence'))$('#prev-sentence').onclick=()=>changeLesson(lesson-1);
if($('#next-sentence'))$('#next-sentence').onclick=()=>{const id=`${grade}-${lesson}`;if(!state.completed.includes(id))state.completed.push(id);activity('sentences',id);if(lesson<5){changeLesson(lesson+1);waveComparison.play('reference');}else{clearRecording();stopAudio();restartComparison();showModal(`<div class="finish-star">🌟</div><h2>${greetingGrade()}练完啦！</h2><p>6 句话，又进步了一点！</p><div class="actions"><button class="btn" id="next-grade">${grade===5?'再练一遍':'试试'+GRADES[grade+1].name} →</button><a class="btn light" href="#challenge" id="sentence-challenge">玩听音</a></div>`,()=>{$('#next-grade').onclick=()=>{if(grade<5)grade++;state.grade=grade;save();$('#modal').close();changeLesson(0);};$('#sentence-challenge').onclick=()=>$('#modal').close();});}};
if($('#start-challenge'))$('#start-challenge').onclick=()=>newChallenge();if($('#review-challenge'))$('#review-challenge').onclick=()=>newChallenge(true);if($('#hear-question'))$('#hear-question').onclick=()=>{const q=challenge.questions[challenge.index],s=SOUNDS[q.id];playAudio(null,`audio/phoneme-${s.id}.mp3`,1,$('#hear-question'),()=>{challenge.heard=true;app.querySelectorAll('.challenge-option').forEach(b=>b.disabled=challenge.answered);if(!challenge.answered)$('#challenge-feedback').textContent='选一个声音吧。';});};app.querySelectorAll('.challenge-option').forEach(b=>b.onclick=()=>{if(!challenge.heard||challenge.answered)return;challenge.answered=true;const q=challenge.questions[challenge.index],s=SOUNDS[q.id],correct=Number(b.dataset.choice)===q.id;if(correct){challenge.score++;state.mistakes=state.mistakes.filter(id=>id!==q.id);}else if(!state.mistakes.includes(q.id))state.mistakes.push(q.id);save();b.classList.add(correct?'correct':'wrong');app.querySelectorAll('.challenge-option').forEach(x=>{x.disabled=true;if(Number(x.dataset.choice)===q.id)x.classList.add('correct');});$('#challenge-feedback').textContent=`${correct?'✓ 对啦！':'再听听看：'} 音标 /${s.symbol}/ · ${s.word}`;$('#next-question').hidden=false;});if($('#next-question'))$('#next-question').onclick=()=>{if(!challenge.answered)return;stopAudio();if(challenge.index===challenge.questions.length-1){challenge.finished=true;activity('challenge');}else{challenge.index++;challenge.answered=false;challenge.heard=false;}render();if(!challenge.finished)$('#hear-question').click();};
if($('#reset-progress'))$('#reset-progress').onclick=()=>showModal('<h2>重新开始学习？</h2><p>这会清空这个浏览器里的音标、句子、复习本和学习天数记录。</p><div class="actions"><button class="btn" id="confirm-reset">确定清空</button><button class="btn light" id="cancel-reset">保留记录</button></div>',()=>{$('#confirm-reset').onclick=()=>{state=fresh();save();challenge=null;$('#modal').close();render();toast('记录已清空，新的探索开始啦。');};$('#cancel-reset').onclick=()=>$('#modal').close();});}
function greetingGrade(){return GRADES[grade].name;}
function changeLesson(n){clearRecording();stopAudio();lesson=Math.max(0,Math.min(5,n));sentenceAnswered=false;render();}
function showModal(html,bindExtra){$('#modal-content').innerHTML=html;$('#modal').showModal();bindExtra?.();}
$('#about').onclick=()=>showModal(`<h2>家长说明</h2><p>先听单独的音标，再点小音标拆开拼读，最后听整个单词。辅音读声音，不读字母名称。</p><p>独立音标采用真人示范录音，来源为 <a href="https://github.com/xiaozhah/phoneme_audio" target="_blank" rel="noopener">phoneme_audio 音频集</a>（该项目注明录音来自牛津词典）。例词和句子以英式语音合成为主，tourist 例词使用同一音频集的录音。采用传统英式 44 音体系，部分现代英式读法有所不同。</p><p>年级是难度参考，不对应特定教材。建议结合老师示范练习。</p><p>进度只保存在本浏览器。录音不上传、不评分，切换音标或句子即清除。波形由真实音频生成，自动略去开头、结尾的安静部分；上下使用相同秒刻度，振幅各自归一化，所以不能比较绝对音量。它只帮助看时长、停顿和声音强弱的变化，不能判断音素是否准确，也不会给发音评分。</p>`);
$('.close').onclick=()=>$('#modal').close();$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').close();};
function route(){if($('#modal').open)$('#modal').close();stopAudio();clearRecording();const target=location.hash.slice(1);page=['home','sounds','sentences','challenge','progress'].includes(target)?target:'home';if(page==='sounds')soundPractice={kind:'phoneme',id:selectedSound,lesson:selectedSound};sentenceAnswered=false;render();window.scrollTo({top:0,behavior:'instant'});}
window.addEventListener('hashchange',route);window.addEventListener('pagehide',()=>{spellingToken++;stopAudio();clearRecording();});route();
